language: java
sudo: no
jdk:
  - oraclejdk8
install:
  - "mvn -N -q io.takari:maven:wrapper -Dmaven=3.3.9"
  - "./mvnw -B -q -DskipTests clean verify dependency:go-offline"
script: './mvnw -B -q clean verify'
