language: java
sudo: no
env:
  - kotlintest_version=1.3.1
jdk:
  - oraclejdk8
install:
  - "mvn -N -q io.takari:maven:wrapper -Dmaven=3.3.9"
script: './mvnw -B -q -Dkotlintest.version=${kotlintest_version} clean test'
