language: java
sudo: no
env:
  - kotlintest_version=1.2.0
  - kotlintest_version=1.2.1-SNAPSHOT
jdk:
  - oraclejdk8
install:
  - "mvn -N -q io.takari:maven:wrapper -Dmaven=3.3.9"
script: './mvnw -B -q -Dkotlintest.version=${kotlintest_version} clean test'
